version: '3'

services:
    db:
        image: postgres:12.0-alpine
        restart: always
        ports:
            - "5432:5432"
        env_file: 
            - ./.env.pg
        volumes:
            - $PWD/postgres:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        command: redis-server --requirepass sOmE_sEcUrE_pAsS
        ports:
            - "6379:6379"
        env_file: 
            - ./.env.redis
        volumes:
            - $PWD/redis/data:/var/lib/redis
            - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    web:
        build: .
        restart: always
        expose:
            - "8000"
        env_file: 
            - ./.env.dev
        depends_on: 
            - db
            - redis
    nginx:
        build: ./nginx
        volumes:
            - $PWD/static_volume:/home/app/web/staticfiles
            - $PWD/media_volume:/home/app/web/mediafiles
        ports:
            - 1337:80
        depends_on:
            - web