version: '3'

services:
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - ./.env.pg
        volumes:
            - ~/noobscribe/postgres:/var/lib/postgresql/data/
    redis:
        image: redis
        restart: always
        command: redis-server --requirepass sOmE_sEcUrE_pAsS
        ports:
            - "6379:6379"
        env_file:
            - ./.env.redis
        volumes:
            - ~/noobscribe/redis/data:/var/lib/redis
            - ~/noobscribe/redis/redis.conf:/usr/local/etc/redis/redis.conf
    web:
        build: ./apps
        restart: always
        expose:
            - "8000"
        env_file:
            - ./.env.dev
        depends_on: 
            - db
            - redis
    nginx:
        image: ./nginx
        restart: always
        volumes:
            - ~/noobscribe/staticfiles:/home/noobscribe/staticfiles
            - ~/noobscribe/mediafiles:/home/noobscribe/mediafiles
        ports:
            - 80:80
        depends_on:
            - web