# Generated by Django 3.0.7 on 2020-06-13 02:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=54, verbose_name='name')),
                ('validity', models.PositiveIntegerField(help_text='Validity in days', verbose_name='validity')),
                ('history_limit', models.PositiveIntegerField(help_text='Validity in days', verbose_name='validity')),
                ('platform', models.CharField(choices=[('YT', 'youtube'), ('FB', 'facebook'), ('IG', 'instagram')], default='YT', editable=False, max_length=4, verbose_name='balance type')),
                ('balance_type', models.CharField(choices=[('FOLL', 'follower'), ('SUBS', 'subscriber'), ('VIEW', 'view')], default='SUBS', editable=False, max_length=4, verbose_name='balance type')),
                ('gain_per_day', models.PositiveIntegerField(help_text='benefit gained per day', verbose_name='gain per day')),
                ('give_per_day', models.PositiveIntegerField(help_text='effort per day', verbose_name='give per day')),
                ('price', models.DecimalField(decimal_places=2, help_text='price base', max_digits=10, verbose_name='price')),
                ('email_report', models.BooleanField()),
                ('whatsapp_report', models.BooleanField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_noobscribe_plans.plan_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
            },
        ),
        migrations.CreateModel(
            name='SubscriberYoutubePlan',
            fields=[
                ('plan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='noobscribe_plans.Plan')),
            ],
            options={
                'verbose_name': 'youtube subscriber plan',
                'verbose_name_plural': 'youtube subscriber plans',
            },
            bases=('noobscribe_plans.plan',),
        ),
        migrations.CreateModel(
            name='ViewYoutubePlan',
            fields=[
                ('plan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='noobscribe_plans.Plan')),
            ],
            options={
                'verbose_name': 'view youtube plan',
                'verbose_name_plural': 'view youtube plans',
            },
            bases=('noobscribe_plans.plan',),
        ),
    ]
