# Generated by Django 3.0.7 on 2020-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobscribe_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriberyoutubeplan',
            options={'verbose_name': 'YouTube Subscriber', 'verbose_name_plural': 'YouTube Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='viewyoutubeplan',
            options={'verbose_name': 'YouTube View', 'verbose_name_plural': 'YouTube Views'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='history_limit',
            field=models.PositiveIntegerField(help_text='History limit in days', verbose_name='history limit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='platform',
            field=models.CharField(choices=[('YT', 'youtube'), ('FB', 'facebook'), ('IG', 'instagram')], default='YT', editable=False, max_length=4, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='price per month', max_digits=10, verbose_name='price'),
        ),
    ]
