# Generated by Django 3.0.7 on 2020-06-16 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('noobscribe_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=54, verbose_name='name')),
                ('unit_of_measure', models.CharField(max_length=25, null=True, verbose_name='unit')),
                ('price', models.DecimalField(decimal_places=2, help_text='price per month', max_digits=10, verbose_name='price')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_noobscribe_plans.product_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'product',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='noobscribe_plans.Product')),
                ('platform', models.CharField(choices=[('YT', 'Youtube'), ('FB', 'Facebook'), ('IG', 'Instagram'), ('SC', 'SoundCloud')], default='YT', max_length=4, verbose_name='platform')),
                ('balance_type', models.CharField(choices=[('FANS', 'Fan'), ('FOLL', 'Follower'), ('SUBS', 'Subscriber'), ('COMM', 'Comment'), ('LIKE', 'Like'), ('DISL', 'Dislike'), ('VIEW', 'View')], default='SUBS', max_length=4, verbose_name='balance type')),
                ('quantity', models.PositiveIntegerField(help_text='quantity', verbose_name='quantity')),
            ],
            options={
                'verbose_name': 'Quota',
                'verbose_name_plural': 'Quota',
            },
            bases=('noobscribe_plans.product',),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='noobscribe_plans.Product')),
                ('validity', models.PositiveIntegerField(help_text='validity', verbose_name='validity')),
                ('member_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='noobscribe_auth.MemberLevel', verbose_name='member level')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Member',
            },
            bases=('noobscribe_plans.product',),
        ),
    ]
